!include "\paa\make.inc"

FLILIBO = \
 flierror.obj\
 addfirst.obj\
 addnext.obj\
 addring.obj\
 allocbuf.obj\
 brunline.obj\
 bufsize.obj\
 comp_ani.obj\
 compbrun.obj\
 complcc.obj\
 compss2.obj\
 create.obj\
 emptyrec.obj\
 fccomp.obj\
 fiicreat.obj\
 finish.obj\
 fliclose.obj\
 flicomp.obj\
 flicomp1.obj\
 fliopen.obj\
 flipstam.obj\
 fliseek1.obj\
 fliseek2.obj\
 flushhdr.obj\
 info.obj\
 infosub.obj\
 isempty.obj\
 isvalid.obj\
 readfirst.obj\
 readhead.obj\
 readnext.obj\
 readunc.obj\
 readunc1.obj\
 skipbrun.obj\
 unbrun.obj\
 uncomp.obj\
 unscbrun.obj\
 userid.obj\
 writerec.obj


ALLO = $(FLILIBO) fliwrap.obj readcolo.obj squaopen.obj flione.obj


libs: pjfli.lib
	@cd
	@echo libs made


pjfli.lib:	$(ALLO)\
			fli.obs\
			pjfli.obs
			wlib /n pjfli.lib @fli.obs @pjfli.obs

