!include "..\inc\make.inc"

EXE  = seq.pdr
OBJ  = seq.obj suffixin.obj blit.obj convbits.obj
LOBJ = seq.obj,suffixin.obj,blit.obj,convbits.obj

$(EXE): $(OBJ)
	wlink @pdr.lnk FILE $(LOBJ) NAME $(EXE)
	copy $(EXE) \paa\resource
