!include "..\inc\make.inc"

EXTCPF = -w3			# all warnings enabled for gluecode
C_IL = $(C_IL);..\..\	# add fliclib root dir to include pathlist

OBJ 	= \
		  ainfinit.obj \
		  cmapupdt.obj \
		  cmapsame.obj \
		  convclk.obj  \
		  errmsg.obj   \
		  errirept.obj \
		  flicclos.obj \
		  fliccre.obj  \
		  flicfini.obj \
		  flicinff.obj \
		  flicinfo.obj \
		  flicname.obj \
		  flicoinf.obj \
		  flicopen.obj \
		  flicrwnd.obj \
		  flicspee.obj \
		  flicwrt1.obj \
		  flicwrtn.obj \
		  playflic.obj \
		  playfram.obj \
		  playnext.obj \
		  playntil.obj \
		  playonce.obj \
		  playtime.obj \
		  poptinit.obj \
		  rastallo.obj \
		  rastbind.obj \
		  rastclip.obj \
		  rastclr.obj  \
		  rastcopy.obj \
		  rastcust.obj \
		  rastonly.obj \
		  rastvirt.obj \
		  vdrvall.obj  \
		  vdrvglue.obj \
		  #endoflist


gluecode.lib: $(OBJ) makefile.
   del	$<
   wlib $< @&&%
$(OBJ)
%

