!include "\paa\make.inc"

O = marqi.obj mucolors.obj rast1lib.obj textbox.obj\
 waitwndo.obj wndo.obj wndodot.obj wndolib.obj wndoclip.obj wscreen.obj

test.exp: wndolib.lib test.obj
	wlinkp @test.lnk

libs: wndolib.lib
	@cd
	@echo libs made

wndolib.lib: 	$(O)\
		 		wndolib.obs
	wlib /n wndolib.lib @wndolib.obs 

