!include "..\inc\make.inc"

!include "obj1list.inc"
!include "obj2list.inc"
!include "obj3list.inc"

util.lib: $(OBJ1) $(OBJ2) $(OBJ3) obj1list.inc obj2list.inc obj3list.inc
	del  $<
	wlib $< @&&%
$(OBJ1)
$(OBJ2)
$(OBJ3)
%
