!include "..\inc\make.inc"

EXE  = anim.pdr
OBJ  = anim.obj convbits.obj unrif.obj unpic.obj
LOBJ = anim.obj,convbits.obj,unrif.obj,unpic.obj

$(EXE): $(OBJ)
	wlink @pdr.lnk FILE $(LOBJ) NAME $(EXE)
	copy $(EXE) \paa\resource
