!include "..\inc\make.inc"

DRIVERO= device.obj raster.obj \
	color.obj dot.obj lovideo.obj \
	hseg.obj getvseg.obj hline.obj rect.obj \
	mask1bli.obj mask2bli.obj blit.obj tblit.obj \
	unbrun.obj unlccomp.obj uncc64.obj uncc256.obj unss2.obj

mcga.drv: $(DRIVERO)
#	fastlink ..\lib\rexentry.obj @driver.lnk -RELEXE mcga.drv
	wlink @..\usual.lnk NAME $< FILE @files.lnk
	copy $< \paa\resource

