!include ..\inc\make.inc

all: breaksub.poe cycle.poe

BREAKO = breaksub.obj

breaksub.poe: $(BREAKO)
	fastlink $(REXSTARTUP) @breaksub.lnk -RELEXE breaksub.poe

CYCLEO = cycle.obj

cycle.poe: $(CYCLEO)
	fastlink $(REXSTARTUP) @cycle.lnk -RELEXE cycle.poe

