
all: ilib host rex

ilib:
	cd \paa\inc
	tcmake ilib
	cd \paa\rexlib

host: ilib
	cd \paa\rexlib\rexhost
	tcmake
	cd ..

rex: ilib
	cd \paa\rexlib\inc
	tcmake
	copy makewc.inc make.inc
	cd ..\syslib
	tcmake
	cd ..\stdiolib
	tcmake
	cd ..\gfxlib
	tcmake
	cd ..\mathlib
	tcmake
	cd ..
