CFLAGS = -ez

!include "make.inc"

libs: widget.lib
	@cd
	@echo made

widget.lib: rexwidge.obj\
		 	widget.obs
	wlib /n widget.lib @widget.obs 

test: widget.rex test.exp

test.exp: test.obj rexwidge.obj 
	wlink @test.lnk option map 
	@echo objlib made

rexdata.c: widget.rex
	run386 \build\bin\rexdump.exp widget.rex rexdata.c cant_load

rexwidge.obj: rexwidge.c rexdata.c

widget.rex: entry.obj widgerex.obj bracket.obj
 	fastlink entry.obj widgerex.obj bracket.obj -DOSORDER -RELEXE widget.rex

