!include "..\..\inc\make.inc"

L = ..\\

libs: $(L)rexhost.lib $(L)rexentry.obj \build\bin\rexdump.exp
	@cd

# *** library linked in with host program that wants to load rexlibs ***

$(L)rexentry.obj:	rexentry.asm\
					rexentry.i
	$(AS) rexentry.asm $(APF)
	copy rexentry.obj $(L)rexentry.obj


REXHOSTO = rexload.obj rexlib.obj keytext.obj

 
$(L)rexhost.lib:	$(REXHOSTO)\
				 	rexhost.obs
 wlib /n $(L)rexhost.lib @rexhost.obs 

\build\bin\rexdump.exp: rexdump.obj
	wlink @rexdump.lnk

