# makefile for Turbo/Borlandc poco

#----------------------------------------------------------------------------
# variables naming source, object, related, and extra files...
#----------------------------------------------------------------------------

!include "pocfiles.inc"

#----------------------------------------------------------------------------
# tweakable things (pathnames, etc)...
#----------------------------------------------------------------------------

WHO 	 = IAN						# IAN or JIM, but I can't remember why.
I		 = c:\borlandc\include\ # header files
L		 = c:\borlandc\lib\ 	# libraries

#----------------------------------------------------------------------------
# command line pieces and rarely-tweaked things...
#----------------------------------------------------------------------------

EXE 	 = poco.exe

CC		 = bcc.exe
CPF 	 = @bcpoco.cfg -D$(WHO) -DVERSION="$(VERSION)"

LINK	 = tlink.exe
LFLAGS	 = /v /L$(L)
LFILES	 = c0l.obj @tcpoco.lnk, poco, poco,
LIBS	 = mathl emu pocofli cl

.c.obj:
	$(CC) $(CPF) -I$(I) $(CFLAGS) {$< }

#----------------------------------------------------------------------------
# rules and targets...
#----------------------------------------------------------------------------

$(EXE): $(OBJ)
	$(LINK) $(LFLAGS) $(LFILES) $(LIBS)

main.obj pocoface.obj pp.obj: pocfiles.inc	 # if version num changes, recompile these

#----------------------------------------------------------------------------
# special rules to make a couple modules different for TC/BC than the
# way we do it for Watcom.	(Covers 386asm code with workalike C code).
#----------------------------------------------------------------------------

runccall.obj: bcrcall.c
	  $(CC) $(CPF) $(CFLAGS) -orunccall.obj bcrcall.c

pocoutil.obj: bcutil.c
	  $(CC) $(CPF) $(CFLAGS) -opocoutil.obj bcutil.c

#----------------------------------------------------------------------------
# special targets for making backups, etc...
#----------------------------------------------------------------------------

cleanup:
	del *.obj

force: cleanup $(EXE)
	@echo

archive distrib:
	- zip -P poco$(VERSION) $(SRC1)
	- zip -P poco$(VERSION) $(SRC2)
	- zip -P poco$(VERSION) $(SRC3)
	- zip -P poco$(VERSION) $(SRC4)
	- zip -P poco$(VERSION) $(SRC5)
	- zip -P poco$(VERSION) $(SRC6)
	- zip -P poco$(VERSION) $(HDR1)
	- zip -P poco$(VERSION) $(EXTRAS)

arcupd:
	- zip -P -f poco$(VERSION) *.*

