!include "\paa\make.inc"

O=   interp.obj readfont.obj shipshap.obj



ps1.exp: $(O) ps1.lnk
	wlink @ps1.lnk
	@cd
	@echo libs made

libs:
	@cd
	@echo libs made

ps1.lib: 	$(O)\
		 		ps1.obs
	del ps1.lib
	wlib ps1.lib @ps1.obs 
