#! /bin/sh
#
#   Remake all AutoCAD shape definitions
#
als -e psfonts/*.pfb | stream -s echo 'Processing \$1' \; readfont psfonts/\$1.pfb shapes/\$1.shp | sh
als -e shapes/*.shp | stream -s 7 shapes/\$1 x >shapes/compile.scr
echo 0 >>shapes/compile.scr
acad . shapes/compile
als -e shapes/*.shx | stream -s style \$1 shapes/\$1 0 1 0 n n n >psfont.scr
echo "style standard  0 1 0 n n n" >>psfont.scr
