!include "..\inc\make.inc"

EXE  = pict.pdr
OBJ  = pict.obj pictutil.obj pictops.obj i86swap.obj pictbmap.obj \
	   bytecopy.obj packline.obj pictsave.obj membsame.obj memwstuf.obj \
	   memwcopy.obj
LOBJ = pict.obj,pictutil.obj,pictops.obj,i86swap.obj,pictbmap.obj,\
	   bytecopy.obj,packline.obj,pictsave.obj,membsame.obj,memwstuf.obj,\
	   memwcopy.obj


$(EXE): $(OBJ)
	wlink @pdr.lnk FILE @&&%
$(LOBJ)
% NAME $(EXE)
	copy $(EXE) \paa\resource
