#CFLAGS= -d2
!include "\paa\make.inc"

O = \
 bhash.obj\
 bhashlkp.obj\
 celalloc.obj\
 colload.obj\
 colsave.obj\
 commonst.obj\
 config.obj\
 cpack.obj\
 cursxlat.obj\
 defltcur.obj\
 devsels.obj\
 drivermu.obj\
 errcfind.obj\
 errcload.obj\
 errcusem.obj\
 errline.obj\
 errtext.obj\
 filemenu.obj\
 flipdr.obj\
 fontreq.obj\
 gifname.obj\
 images.obj\
 initcmap.obj\
 jiffycon.obj\
 mainret.obj\
 mathhost.obj\
 minitime.obj\
 palread.obj\
 palwrite.obj\
 picpdr.obj\
 pdrmenu.obj\
 pdrpic.obj\
 pencel.obj\
 pichead.obj\
 picinfo.obj\
 picload.obj\
 picsave.obj\
 qchoice.obj\
 qreqnum.obj\
 qreqstr.obj\
 qrequnum.obj\
 qscroll.obj\
 rastcurs.obj\
 resexist.obj\
 resource.obj\
 resoureq.obj\
 scodes.obj\
 scrainfo.obj\
 scrclose.obj\
 screenmu.obj\
 scrninit.obj\
 smucont.obj\
 smuerr.obj\
 smultbox.obj\
 smupull.obj\
 smuqreqn.obj\
 smuqrecn.obj\
 smuqreqs.obj\
 smuqrunu.obj\
 smutext.obj\
 smuvqren.obj\
 smuyesno.obj\
 smuwaitb.obj\
 startup.obj\
 temprcel.obj\
 timefunc.obj\
 timeslid.obj\
 toglmenu.obj\
 ttextf.obj\
 smuttext.obj\
 vqreqnum.obj\
 vqreqstr.obj


libs: pjhigh.lib
	@cd
	@echo made

## two versions of local pdr one read and will write one frame
## the other is read/write

## items dependent on release.h

startup.obj: $(IL)release.h

pjhigh.lib: $(O)\
			pjhigh.obs
	wlib /n pjhigh.lib @pjhigh.obs

