
!include "..\inc\make.inc"

# LIST OF OBJECT FILES

DRIVERO = device.obj raster.obj hgsmodep.obj \
	hgsdots.obj hgssegs.obj hgslines.obj hgsrects.obj hgsdcomp.obj \
	maskblit.obj

# PRIMARY TARGET...

hgsc.drv: $(DRIVERO)
#	fastlink ..\lib\rexentry.obj @driver.lnk -RELEXE hgsc.drv
	wlink @..\usual.lnk NAME $< FILE @files.lnk
#	copy $< \paa\resource

archive:
	zip hgscdrv.zip *.c *.asm *.h *.inc *.lnk *.bat makefile

