VERSION = 24

!include "..\inc\make.inc"

# LIST OF OBJECT FILES

COMMONO = drvcomn.obj drvdots.obj drvlines.obj drvsegs.obj drvvert.obj \
		  drvxorr.obj drvunss2.obj drvunbrn.obj drvunlcc.obj \
		  drvrast.obj drvblita.obj drvblitc.obj

# LIST OF SOURCE FILES

SOURCE2 = drvcomn.asm drvdots.asm drvlines.asm drvsegs.asm drvvert.asm
SOURCE3 = drvxorr.asm drvunss2.asm drvunbrn.asm drvunlcc.asm \
		  drvrast.asm drvblita.asm drvblitc.c
EXTRAS	= *.h *.i *.lnk *.obs makefile versions.doc

# LINK RULES

drvcomn.lib: $(COMMONO) drvcomn.obs makefile
	wlib /n drvcomn.lib @drvcomn.obs

$(COMMONO): drvcomn.h drvcomn.i

archive:
	zip drv$(VERSION) $(SOURCE2)
	zip drv$(VERSION) $(SOURCE3)
	zip drv$(VERSION) $(EXTRAS)
