!include "..\..\inc\make.inc"

L = ..\\

libs: $(L)stdiolib.lib
	@cd

# *** object files for "_a_a_stdiolib" calls ***

STDIOLIBO = clearerr.obj\
 errcode.obj fclose.obj feof.obj ferror.obj fflush.obj fgetc.obj fgets.obj\
 fopen.obj fprintf.obj fputc.obj fputs.obj fread.obj fseek.obj ftell.obj\
 fwrite.obj printf.obj ptoerrno.obj rewind.obj sprintf.obj ungetc.obj\
 fferror.obj ffopen.obj ffread.obj ffreados.obj ffseek.obj fftell.obj\
 ffwrite.obj ffwriteo.obj

$(STDIOLIBO): $(IL)stdiolib.i $(IL)stdiolib.h


$(L)stdiolib.lib:	$(STDIOLIBO)\
					stdiolib.obs
 del $(L)stdiolib.lib
 wlib $(L)stdiolib.lib @stdiolib.obs 

