!include "..\inc\make.inc"

EXE  = sld.pdr
OBJ  = sld.obj concave.obj convex.obj
LOBJ = sld.obj,concave.obj,convex.obj

$(EXE): $(OBJ)
	wlink @pdr.lnk FILE $(LOBJ) NAME $(EXE)
	copy $(EXE) \paa\resource
