!include "..\inc\make.inc"

EXTCPF = -w3			# all warnings enabled for gluecode
C_IL = $(C_IL);..\..\	# add fliclib root dir to include pathlist

OBJ3S	= memglu3s.obj	rtlglu3s.obj
OBJ3R	= memglu3r.obj	rtlglu3r.obj
OBJPLS	= gs_pls.obj
OBJDPMI = gs_dpmi.obj

all: glue3s.lib glue3r.lib gluepls.lib gluedpmi.lib

glue3s.lib: $(OBJ3S) makefile.
	del  $<
	wlib $< $(OBJ3S)

glue3r.lib: $(OBJ3R) makefile.
	del  $<
	wlib $< $(OBJ3R)

gluepls.lib: $(OBJPLS) makefile.
	del $<
	wlib $< $(OBJPLS)

gluedpmi.lib: $(OBJDPMI) makefile.
	del $<
	wlib $< $(OBJDPMI)

memglu3s.obj: memglu.c
		$(CC) memglu.c $(CPF) -I$(C_IL) $(EXTCPF) $(CFLAGS) -3s /fo=$<

rtlglu3s.obj: rtlglu.c
		$(CC) rtlglu.c $(CPF) -I$(C_IL) $(EXTCPF) $(CFLAGS) -3s /fo=$<

memglu3r.obj: memglu.c
		$(CC) memglu.c $(CPF) -I$(C_IL) $(EXTCPF) $(CFLAGS) -3r /fo=$<

rtlglu3r.obj: rtlglu.c
		$(CC) rtlglu.c $(CPF) -I$(C_IL) $(EXTCPF) $(CFLAGS) -3r /fo=$<

