!include "..\..\inc\make.inc"

L = ..\\

# Note: assembler build is first in list

libs: built_asms $(L)mathhost.lib
	@cd

## built assembler modules made by batch file and little assembler file

BASMS = acos.asm asin.asm atan.asm atan2.asm ceil.asm cos.asm cosh.asm\
 		exp.asm fabs.asm floor.asm fmod.asm frexp.asm ldexp.asm log.asm\
 		log10.asm modf.asm pow.asm sin.asm sinh.asm sqrt.asm tan.asm tanh.asm

built_asms: $(BASMS)
	@donothin

acos.asm: rmlcall.bat rmljump.i 
	rmlcall acos

asin.asm: rmlcall.bat rmljump.i 
	rmlcall asin

atan.asm: rmlcall.bat rmljump.i 
	rmlcall atan

atan2.asm: rmlcall.bat rmljump.i 
	rmlcall atan2

ceil.asm: rmlcall.bat rmljump.i 
	rmlcall ceil

cos.asm: rmlcall.bat rmljump.i 
	rmlcall cos

cosh.asm: rmlcall.bat rmljump.i 
	rmlcall cosh

exp.asm: rmlcall.bat rmljump.i 
	rmlcall exp

fabs.asm: rmlcall.bat rmljump.i 
	rmlcall fabs

floor.asm: rmlcall.bat rmljump.i 
	rmlcall floor

fmod.asm: rmlcall.bat rmljump.i 
	rmlcall fmod

frexp.asm: rmlcall.bat rmljump.i 
	rmlcall frexp

ldexp.asm: rmlcall.bat rmljump.i 
	rmlcall ldexp

log.asm: rmlcall.bat rmljump.i 
	rmlcall log

log10.asm: rmlcall.bat rmljump.i 
	rmlcall log10

modf.asm: rmlcall.bat rmljump.i 
	rmlcall modf

pow.asm: rmlcall.bat rmljump.i 
	rmlcall pow

sin.asm: rmlcall.bat rmljump.i 
	rmlcall sin

sinh.asm: rmlcall.bat rmljump.i 
	rmlcall sinh

sqrt.asm: rmlcall.bat rmljump.i 
	rmlcall sqrt

tan.asm: rmlcall.bat rmljump.i 
	rmlcall tan

tanh.asm: rmlcall.bat rmljump.i 
	rmlcall tanh

# *** object files for "_a_a_mathlib" calls ***

CALLO = acos.obj asin.obj atan.obj atan2.obj ceil.obj cos.obj cosh.obj\
 exp.obj fabs.obj floor.obj fmod.obj frexp.obj ldexp.obj log.obj log10.obj\
 modf.obj pow.obj sin.obj sinh.obj sqrt.obj tan.obj tanh.obj 

LOCALO = watco387.obj wc_fchop.obj highc387.obj hc_fchop.obj

$(CALLO): $(IL)mathhost.i

hc_fchop.obj: hc_fchop.asm
	$(AS) $* $(APF) -387

wc_fchop.obj: wc_fchop.asm
	$(AS) $* $(APF) -387

# *** ansi math lib provided by host Note: assemblers listed first


$(L)mathhost.lib: $(BASMS) $(CALLO) $(LOCALO)\
				  mathhost.obs
 del $(L)mathhost.lib
 wlib $(L)mathhost.lib @mathhost.obs 


