!include "..\inc\make.inc"

VERSION = 15	# used in making backup filenames

OBJ 	= tifread.obj tifwrite.obj mtoscrn.obj mfrmscrn.obj rgblines.obj \
		  packbits.obj lzwcmprs.obj tifutil.obj unhufman.obj unlzw.obj
LOBJ	= tifread.obj,tifwrite.obj,mtoscrn.obj,mfrmscrn.obj,rgblines.obj, \
		  packbits.obj,lzwcmprs.obj,tifutil.obj,unhufman.obj,unlzw.obj

SOURCE1 = tiff.c tifread.c tifwrite.c packbits.c mtoscrn.c mfrmscrn.c
SOURCE2 = rgblines.c tifutil.asm unhufman.asm lzwcmprs.c unlzw.asm
HDRS	= tiff.h
EXTRAS	= makefile versions.doc tiftest.c tiff.lnk

#----------------------------------------------------------------------------
# primary target, make both PDRs that come from this source...
#----------------------------------------------------------------------------

all: tiff.pdr tiffgrey.pdr

#----------------------------------------------------------------------------
# TIFF.PDR target... Link togther modules for color-mapped-output PDR
#----------------------------------------------------------------------------

tiff.pdr: $(OBJ) tiff.obj
	wlink @pdr.lnk NAME tiff.pdr FILE @&&%
tiff.obj,$(LOBJ)
%
	copy tiff.pdr \paa\resource

#----------------------------------------------------------------------------
# TIFFGREY.PDR target... Link together modules for greyscale-output PDR
#----------------------------------------------------------------------------

tiffgrey.pdr: $(OBJ) tiffgrey.obj
	wlink @pdr.lnk NAME tiffgrey.pdr FILE @&&%
tiffgrey.obj,$(LOBJ)
%
	copy tiffgrey.pdr \paa\resource

#----------------------------------------------------------------------------
# TIFF.OBJ target... Compile TIFF.C to TIFF.OBJ with CMAPPED macro defined
#----------------------------------------------------------------------------

tiff.obj: tiff.c
		$(CC) tiff.c $(CPF) -I$(C_IL) -DCMAPPED $(EXTCPF) $(CFLAGS)

#----------------------------------------------------------------------------
# TIFFGREY.OBJ target... Compile TIFF.C to TIFFGREY.OBJ with GREY macro defined
#----------------------------------------------------------------------------

tiffgrey.obj: tiff.c
		$(CC) tiff.c $(CPF) -I$(C_IL) -DGREY $(EXTCPF) $(CFLAGS) /fo=tiffgrey.obj

#----------------------------------------------------------------------------
# ARCHIVE target...back up the source
#----------------------------------------------------------------------------

archive:
	zip tifdrv$(VERSION) $(SOURCE1)
	zip tifdrv$(VERSION) $(SOURCE2)
	zip tifdrv$(VERSION) $(HDRS) $(EXTRAS)

