!include "\paa\make.inc"


ilib: aasyslib.i errcodes.i gfxlib.i mathhost.i procblit.i raster.i\
	rastlib.i stdiolib.i wndo.i
	@cd
	@echo include made

cleanout:
	del aasyslib.i
	del errcodes.i
	del gfxlib.i 
	del mathhost.i 
	del procblit.i 
	del raster.i
	del rastlib.i 
	del stdiolib.i 
	del wndo.i 

force: cleanout ilib

aasyslib.i: rexlib.h aasyslib.h aasyslib.c aasyslib.ih 
 	$(CC) $*.c $(CPF)
 	wlink NAME $*.exp @watcom.lnk FILE $*.obj 
 	run386 $*.exp $*.i
 	copy $*.i+$*.ih $*.i
	del $*.exp
	del $*.obj

errcodes.i: errcodes.h errcodes.c  
	$(CC) $*.c $(CPF)
	wlink NAME $*.exp @watcom.lnk FILE $*.obj 
	run386 $*.exp $*.i
	del $*.exp
	del $*.obj

gfxlib.i: rexlib.h gfxlib.h gfxlib.c gfxlib.ih 
 	$(CC) $*.c $(CPF)
 	wlink NAME $*.exp @watcom.lnk FILE $*.obj 
 	run386 $*.exp $*.i
 	copy $*.i+$*.ih $*.i
	del $*.exp
	del $*.obj

mathhost.i: rexlib.h mathhost.h mathhost.c mathhost.ih 
 	$(CC) $*.c $(CPF)
 	wlink NAME $*.exp @watcom.lnk FILE $*.obj 
 	run386 $*.exp $*.i
 	copy $*.i+$*.ih $*.i
	del $*.exp
	del $*.obj

procblit.i: procblit.h procblit.c  
	$(CC) $*.c $(CPF)
	wlink NAME $*.exp @watcom.lnk FILE $*.obj 
	run386 $*.exp $*.i
	del $*.exp
	del $*.obj

rastlib.i: rastlib.h rastlib.c rastlib.ih 
	$(CC) $*.c $(CPF)
	wlink NAME $*.exp @watcom.lnk FILE $*.obj 
	run386 $*.exp $*.i
 	copy $*.i+$*.ih $*.i
	del $*.exp
	del $*.obj

raster.i: raster.h raster.c raster.ih 
	$(CC) $*.c $(CPF)
	wlink NAME $*.exp @watcom.lnk FILE $*.obj 
	run386 $*.exp $*.i
 	copy $*.i+$*.ih $*.i
	del $*.exp
	del $*.obj

stdiolib.i: rexlib.h stdiolib.h stdiolib.c stdiolib.ih 
 	$(CC) $*.c $(CPF)
 	wlink NAME $*.exp @watcom.lnk FILE $*.obj 
 	run386 $*.exp $*.i
 	copy $*.i+$*.ih $*.i
	del $*.exp
	del $*.obj

wndo.i: wndo.h wndo.c   
 	$(CC) $*.c $(CPF)
	wlink NAME $*.exp @watcom.lnk FILE $*.obj 
	run386 $*.exp $*.i
	del $*.exp
	del $*.obj

