!include ..\inc\make.inc

CFLAGS = /w3

EXE  = flicplay.poe
OBJ  = flicplay.obj playfunc.obj openfunc.obj
LOBJ = flicplay.obj,playfunc.obj,openfunc.obj

LIB  = \paa\flic386p\flic386p.lib

$(EXE): $(OBJ)
	wlink @poe.lnk FILE $(LOBJ) LIB $(LIB) NAME $(EXE) OPTION MAP

