!include "..\inc\make.inc"

EXE  = degas.pdr
OBJ  = degas.obj suffixin.obj unpic.obj
LOBJ = degas.obj,suffixin.obj,unpic.obj

$(EXE): $(OBJ)
	wlink @pdr.lnk FILE $(LOBJ) NAME $(EXE)
	copy $(EXE) \paa\resource
