!include "..\inc\make.inc"


all: video7.drv vram4.drv
	@echo made video7.drv  and vram4.drv

COMMONO = \
 vramcmap.obj vramsubs.obj vrampdot.obj vramgdot.obj vramdhli.obj\
 vramxhli.obj vramputh.obj vramgeth.obj vrammsk1.obj vramss2.obj\
 vramddhl.obj vrambank.obj vramuncc.obj vramunc2.obj

VRAMO = device.obj raster.obj $(COMMONO)

video7.drv: $(VRAMO)
#	fastlink ..\lib\rexentry.obj @driver.lnk -RELEXE video7.drv
	wlink @..\usual.lnk NAME $< FILE @files.lnk
	copy $< \paa\resource

VRAM4O = device4.obj raster4.obj $(COMMONO)

vram4.drv: $(VRAM4O)
#	fastlink ..\lib\rexentry.obj @driver4.lnk -RELEXE vram4.drv
	wlink @..\usual.lnk NAME $< FILE @files4.lnk
#	copy $< \paa\resource
