!include "..\inc\make.inc"

C_IL = $(C_IL);..\drvcomn\		# add drvcomn dir to C include path
A_IL = $(A_IL),..\drvcomn\		# add drvcomn dir to ASM include path

OBJ   = vesavdev.obj vesaintf.obj vesamode.obj # base vesa routines

PLOBJ = plralloc.obj plint10.obj	# pharlap-specific modules
CBOBJ = cbralloc.obj cbint10.obj	# codebuilder-specific modules
WCOBJ = wcralloc.obj wcint10.obj	# watcom4g-specific modules

all: vesavdev.lib plvesa.lib cbvesa.lib wcvesa.lib

vesavdev.lib: $(OBJ) makefile.
	del  $<
	wlib $< $(OBJ)

plvesa.lib: $(PLOBJ)
	del  $<
	wlib $< $(PLOBJ)

cbvesa.lib: $(CBOBJ)
	del  $<
	wlib $< $(CBOBJ)

wcvesa.lib: $(WCOBJ)
	del  $<
	wlib $< $(WCOBJ)
