CFLAGS = -Ilib -DPJ_PDR
!include "..\inc\make.inc"

EXE  = jpeg.pdr
OBJ  = pdr.obj jpegread.obj jpegsave.obj error.obj jpegres.obj
LOBJ = pdr.obj,jpegread.obj,jpegsave.obj,error.obj,jpegres.obj

$(EXE): $(OBJ)
	wlink @pdr.lnk FILE $(LOBJ) LIBRARY lib\libjpeg.lib,clib3s.lib NAME $(EXE)
	copy $(EXE) \paa\resource
