CFLAGS = -Ilib -DPJ_PDR
!include "..\inc\make.inc"

EXE  = savejpeg.pdr
OBJ  = pdr.obj
LOBJ = pdr.obj

$(EXE): $(OBJ)
	wlink @pdr.lnk FILE $(LOBJ) LIBRARY lib\libjpeg.lib,clib3s.lib NAME $(EXE)
	copy $(EXE) \paa\resource
