#CFLAGS= -d2
!include "\paa\make.inc"

libs: trdfile.lib doslfile.lib dosfile.lib 
	 @cd
 	 @echo libs made

## dos file io modules ****

DOSO = \
 dosclose.obj doscreat.obj dosctflp.obj dosdelet.obj dosdfree.obj\
 dosetdir.obj dosetdta.obj dosfirst.obj dosgetdr.obj dosgtdir.obj\
 dosisdev.obj dosmkdir.obj dosnext.obj dosopen.obj dosread.obj dosrenam.obj\
 dosseek.obj dossetdr.obj dostell.obj doswrite.obj dosetdri.obj dostrunc.obj

## "j" dos device and directory level calls that call dos only 

JFDEVO = \
 jdevget.obj jdevset.obj jdirset.obj jdevlist.obj jdevsget.obj

## file name parseing modules (string functions etc) ***

FPARSEO = \
 fpaddsub.obj fparsdev.obj fparsdir.obj fpconcat.obj fpdirlen.obj\
 fpfulfil.obj fpgetdir.obj fpgetful.obj fpgetnam.obj fpincnam.obj\
 fpissuff.obj fpmkfile.obj fpnmerge.obj fpnsplit.obj fppfxlen.obj\
 fpremnam.obj fpspltcp.obj fpspltpa.obj fpsuffix.obj fpsufget.obj\
 fpsufhas.obj fpsuffin.obj fpsufrem.obj fpnamein.obj fpsetnam.obj 

## jfile modules that only handle dos files, NO internal ram disk NO temp
## file handling.
## note dfgetdrv is a filepath module but is here because of the temp drive 
## handling

JFILEDO = \
 dfdelete.obj dfexists.obj dfile.obj dfisfixd.obj dfread.obj dfrename.obj\
 dfrwmode.obj dfseek.obj dfsize.obj dfstdio.obj dftell.obj dftrdmem.obj\
 dftrdumm.obj dfwrite.obj dfgetdrv.obj

## jfile io modules that have ram disk temp file handling and temp file handing
## this calls doso modules for operating system calls

## note fpgetdrv is a filepath module but is here because of the temp drive 
## handling

JFILETRO = \
 jfile.obj rfile.obj tfile.obj fpgetdrv.obj

## jfile utilities that call jfile functions ****

JFUTILSO = \
 aasyslib.obj \
 jfcopy.obj   jfcopyin.obj jfcpdato.obj jfcpfile.obj jfcpydat.obj\
 jfinsert.obj jfpisfix.obj jfrdgulp.obj jfreadec.obj jfreados.obj\
 jfwrite0.obj jfwritec.obj jfwritos.obj jfwrtglp.obj jfclosez.obj\
 unchunk.obj unchcopy.obj unchupd.obj unchread.obj wrtchunk.obj
 
## ansi spec standard io file system that calls jfile low level routines **** 

LFILEO = \
 lflush.obj lfgetc.obj lfgets.obj lfile.obj lfprintf.obj lfputc.obj\
 lfputs.obj lfread.obj lfrewind.obj lfseek.obj lfsoprtf.obj lfstdfil.obj\
 lftell.obj lfungetc.obj lfvprtf.obj lfwrite.obj
 
## ffile shels around ansi file routines that handle errors and have
## other niceties we like in pj *****

## around lstdio.h **** 

FLFILEO = \
 flopen.obj flread.obj flreados.obj flseek.obj fltell.obj\
 flwrite.obj flwriteo.obj flstdiol.obj

flopen.obj:	ffopen.c\
			$(IL)lstdio.h
	 $(CC) ffopen.c $(CPF) -dUSE_LFILE -fo=$*.obj

flread.obj:	ffread.c\
 			$(IL)lstdio.h
	$(CC) ffread.c $(CPF) -dUSE_LFILE -fo=$*.obj

flreados.obj: ffreados.c\
			$(IL)lstdio.h
 	$(CC) ffreados.c $(CPF) -dUSE_LFILE -fo=$*.obj

flseek.obj:	ffseek.c\
			$(IL)lstdio.h
	 $(CC) ffseek.c $(CPF) -dUSE_LFILE -fo=$*.obj

fltell.obj:	fftell.c\
			$(IL)lstdio.h
	 $(CC) fftell.c $(CPF) -dUSE_LFILE -fo=$*.obj

flwrite.obj:	ffwrite.c\
				$(IL)lstdio.h
	 $(CC) ffwrite.c $(CPF) -dUSE_LFILE -fo=$*.obj

flwriteo.obj:	ffwriteo.c\
				$(IL)lstdio.h
	 $(CC) ffwriteo.c $(CPF) -dUSE_LFILE -fo=$*.obj

flstdiol.obj: ffstdiol.c\
				$(IL)lstdio.h
	 $(CC) ffstdiol.c $(CPF) -dUSE_LFILE -fo=$*.obj

## around stdio.h io fopen etc ******

FFILEO = \
 ffopen.obj ffread.obj ffreados.obj ffseek.obj fftell.obj\
 ffwrite.obj ffwriteo.obj ffstdiol.obj


#** library with temp and ram file handling file system and all utilities *

trdfile.lib: makefile\
			 $(DOSO) dos.obs\
			 $(JFDEVO) jdevice.obs\
			 $(FPARSEO) fparse.obs\
			 $(JFILETRO) jfiletrd.obs\
			 $(JFUTILSO) jfutils.obs\
			 $(LFILEO) lfile.obs\
			 $(FLFILEO) flfile.obs
 @copy dos.obs+jdevice.obs+fparse.obs+jfiletrd.obs trdfile.lbc
 @copy trdfile.lbc+jfutils.obs+lfile.obs+flfile.obs trdfile.lbc
 @del trdfile.lib
 wlib trdfile.lib @trdfile.lbc 
 @del trdfile.lbc

#** library with dos and lstdio file system and all utilities *

doslfile.lib:	makefile\
				$(DOSO) dos.obs\
				$(JFDEVO) jdevice.obs\
				$(FPARSEO) fparse.obs\
				$(JFILEDO) jfiledos.obs\
				$(JFUTILSO) jfutils.obs\
				$(LFILEO) lfile.obs\
				$(FLFILEO) flfile.obs
 @copy dos.obs+jdevice.obs+fparse.obs+jfiledos.obs doslfile.lbc
 @copy doslfile.lbc+jfutils.obs+lfile.obs+flfile.obs doslfile.lbc
 @del doslfile.lib
 wlib doslfile.lib @doslfile.lbc 
 @del doslfile.lbc

#** library with dos and stdio (no lfile) file system and all utilities *

dosfile.lib:	makefile\
				$(DOSO) dos.obs\
				$(JFDEVO) jdevice.obs\
				$(FPARSEO) fparse.obs\
				$(JFILEDO) jfiledos.obs\
				$(JFUTILSO) jfutils.obs\
		   		$(FFILEO) ffile.obs
 @copy dos.obs+jdevice.obs+fparse.obs+jfiledos.obs dosfile.lbc
 @copy dosfile.lbc+jfutils.obs+ffile.obs dosfile.lbc
 @del dosfile.lib
 wlib dosfile.lib @dosfile.lbc 
 @del doslfile.lbc

