# Add .lst to suffixes.  wmake requires that we clear the list first in
# order to add it in the right order.
.SUFFIXES:
.SUFFIXES: .lst .obj .asm .c

CFLAGS= -d2
!include \paa\inc\makewc.inc

# Force wcc386p because some modules are too big for wcc386.
CC = wcc386p

O = test.obj a3d.obj a3ddat.obj alt.obj&
 arctan.obj auto.obj autoseg.obj blue.obj browse.obj broadcas.obj brush.obj&
 celmenu.obj celpaste.obj celpull.obj celtrans.obj cfit.obj&
 cursor.obj cutcurs.obj cleanup.obj cluster.obj composit.obj&
 composmu.obj csort.obj cthread.obj&
 ellipse.obj&
 files.obj findfree.obj fli.obj&
 flicel.obj flicelio.obj fli.obj flipath.obj flood.obj freem.obj flxovlay.obj&
 gel.obj geometry.obj globals.obj grid.obj hitext.obj&
 hotkey.obj inkcashe.obj inkopts.obj&
 inkdot.obj inkdot2.obj macro.obj main.obj mainpull.obj vmarqi.obj mask.obj &
 messages.obj multimen.obj muparts.obj names.obj onepal.obj&
 options.obj overlay.obj palet2.obj pencel.obj&
 penopts.obj pentools.obj penwndo.obj picfiles.obj pjfont.obj&
 qconfig.obj qmacro.obj qmenu.obj&
 poly.obj polyrub.obj polytool.obj pstamp.obj&
 quickdat.obj random.obj rcel.obj resource.obj redo.obj render.obj&
 savefli.obj saveseg.obj selbrush.obj  sep.obj&
 sizemenu.obj spiral.obj spline.obj tempflx.obj&
 tempname.obj textedit.obj textfile.obj thikline.obj tileink.obj time.obj&
 timemenu.obj title.obj truecolor.obj tseg.obj tween.obj tweendat.obj&
 tweenhi.obj tweenlo.obj tweenmag.obj vfeelme.obj vpaint.obj&
 vpsubs.obj vsetting.obj vsetfnam.obj writeflx.obj zoom.obj

POCOOBJS = &
 pocoa3d.obj pocoalt.obj pocoblit.obj pococel.obj pocodos.obj&
 pocodraw.obj pocofile.obj pocoflic.obj pocofunc.obj pocogvar.obj&
 pocomode.obj pocorex.obj pocotext.obj pocotime.obj&
 pocotur.obj pocotwee.obj pocouser.obj pocolibs.obj pocoqnum.obj&
 qpoco.obj qpocoed.obj

objlib: .symbolic $(O) status.obj
	@cd

#items dependent on release.h

auto.obj celpaste.obj hotkey.obj messages.obj penopts.obj status.obj test.obj&
 vpaint.obj: &
	$(IL)release.h

