!include "\paa\inc\make.inc"


all:  aasyslib.i animinfo.h cmap.h errcodes.h errcodes.i ffile.h filemode.h\
	filepath.h gfx.h gfxlib.i hliblist.h idriver.h input.h jfile.h\
	abcdregs.i linklist.h\
	mathhost.i picdrive.h pocolib.h pocorex.h ptrmacro.h rastcall.h\
	raster.h raster.i rastlib.h rastlib.i rcel.h rectang.h regs.h rexlib.h\
	serial.h stdiolib.i stdmacro.i stdtypes.h truepdr.h useful.i \
	usehlib.h vdevice.h \
	vdevinfo.h compiler.h pjinline.h
 @cd


cleanout:
	del abcdregs.i
	del aasyslib.i
	del animinfo.h
	del cmap.h
	del errcodes.h
	del errcodes.i
	del ffile.h
	del filemode.h
	del filepath.h
	del gfx.h
	del gfxlib.i
	del hliblist.h
	del idriver.h
	del input.h
	del jfile.h
	del linklist.h
	del mathhost.i
	del picdrive.h
	del pocolib.h
	del pocorex.h
	del ptrmacro.h
	del rastcall.h
	del raster.h
	del raster.i
	del rastlib.h
	del rastlib.i
	del rcel.h
	del rectang.h
	del regs.h
	del rexlib.h
	del serial.h
	del stdiolib.i
	del stdmacro.i
	del stdtypes.h
	del truepdr.h
	del useful.i
	del usehlib.h
	del vdevice.h
	del vdevinfo.h
	del compiler.h
	del pjinline.h

force: cleanout all


aasyslib.i: $(IL)aasyslib.i
	copy $(IL)$*.i $*.i

abcdregs.i: $(IL)abcdregs.i
	copy $(IL)$*.i $*.i

animinfo.h: $(IL)animinfo.h\
			rexlib.mac
	cmacro $(IL)$*.h rexlib.mac -o $*.h

cmap.h:  $(IL)cmap.h
	copy $(IL)$*.h $*.h

errcodes.h: $(IL)errcodes.h\
			rexlib.mac
	cmacro $(IL)$*.h rexlib.mac -o $*.h

errcodes.i: $(IL)errcodes.i
	copy $(IL)$*.i $*.i

ffile.h:  $(IL)ffile.h
	copy $(IL)$*.h $*.h

filemode.h: $(IL)filemode.h\
			jfile.mac
	cmacro $(IL)$*.h jfile.mac -o $*.h

filepath.h: $(IL)filepath.h\
			jfile.mac
	cmacro $(IL)$*.h jfile.mac -o $*.h

gfx.h: $(IL)gfx.h\
		  gfx.mac
	cmacro $(IL)$*.h gfx.mac -o $*.h

gfxlib.i: $(IL)gfxlib.i
	copy $(IL)$*.i $*.i

hliblist.h: $(IL)hliblist.h
	copy $(IL)$*.h $*.h

idriver.h: $(IL)idriver.h\
			rexlib.mac
	cmacro $(IL)$*.h rexlib.mac -o $*.h

input.h: $(IL)input.h\
			rexlib.mac
	cmacro $(IL)$*.h rexlib.mac -o $*.h

jfile.h: $(IL)jfile.h\
			jfile.mac
	cmacro $(IL)$*.h jfile.mac -o $*.h

linklist.h: $(IL)linklist.h\
			rexlib.mac
	cmacro $(IL)$*.h rexlib.mac -o $*.h

mathhost.i: $(IL)mathhost.i
	copy $(IL)$*.i $*.i

picdrive.h: $(IL)picdrive.h\
			rexlib.mac
	cmacro $(IL)$*.h rexlib.mac -o $*.h

pocolib.h: $(IL)pocolib.h\
			rexlib.mac
	cmacro $(IL)$*.h rexlib.mac -o $*.h

pocorex.h: $(IL)pocorex.h\
			rexlib.mac
	cmacro $(IL)$*.h rexlib.mac -o $*.h

ptrmacro.h: $(IL)ptrmacro.h\
			rexlib.mac
	cmacro $(IL)$*.h rexlib.mac -o $*.h

rastcall.h: $(IL)rastcall.h\
			rastcall.mac
	cmacro $(IL)$*.h rastcall.mac -o $*.h

raster.h: $(IL)raster.h\
			raster.mac
	cmacro $(IL)$*.h raster.mac -o $*.h

raster.i:  $(IL)raster.i
	copy $(IL)$*.i $*.i

rastlib.h: $(IL)rastlib.h\
			rexlib.mac
	cmacro $(IL)$*.h rexlib.mac -o $*.h

rastlib.i:	$(IL)rastlib.i
	copy $(IL)$*.i $*.i

regs.h:  $(IL)regs.h
	copy $(IL)$*.h $*.h

rexlib.h: $(IL)rexlib.h\
			rexlib.mac
	cmacro $(IL)$*.h rexlib.mac -o $*.h

rcel.h: $(IL)rcel.h\
			rexlib.mac
	cmacro $(IL)$*.h rexlib.mac -o $*.h

rectang.h: $(IL)rectang.h\
			rexlib.mac
	cmacro $(IL)$*.h rexlib.mac -o $*.h

serial.h:  $(IL)serial.h
	copy $(IL)$*.h $*.h

stdiolib.i:  $(IL)stdiolib.i
	copy $(IL)$*.i $*.i

stdmacro.i:  $(IL)stdmacro.i
	copy $(IL)$*.i $*.i

stdtypes.h: $(IL)stdtypes.h\
			rexlib.mac
	cmacro $(IL)$*.h rexlib.mac -o $*.h

truepdr.h: $(IL)truepdr.h\
			rexlib.mac
	cmacro $(IL)$*.h rexlib.mac -o $*.h

usehlib.h: $(IL)usehlib.h
	copy $(IL)$*.h $*.h

useful.i:  $(IL)useful.i
	copy $(IL)$*.i $*.i

vdevice.h: $(IL)vdevice.h\
			rexlib.mac
	cmacro $(IL)$*.h rexlib.mac -o $*.h

vdevinfo.h: $(IL)vdevinfo.h\
			rexlib.mac
	cmacro $(IL)$*.h rexlib.mac -o $*.h

compiler.h:  $(IL)compiler.h
	copy $(IL)$*.h $*.h

pjinline.h:  $(IL)pjinline.h
	copy $(IL)$*.h $*.h

