#-----------------------------------------------------------------------------
# Watcom C -3s Makefile for FLC386PS example programs using Phar Lap extender.
#-----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
# These macros and rules are for the watcom 386 c compiler and wmake...
#-----------------------------------------------------------------------------

C_IL	= ..\ # include files path for C
A_IL	= ..\ # include files path for ASM

LFILE	= ..\flc386ps.lib	# lib for pharlap extender, stack parms

CC		= wcc386p
CPF 	= -j -ox -fpi -w2 -3s
EXTCPF	= -DUSING_PHARLAP

.c.obj:
	$(CC) $*.c $(CPF) -I$(C_IL) $(EXTCPF) $(CFLAGS)

AS	= 386asm
APF = -80386 -NOLIST -TWOCASE

.asm.obj:
	$(AS) $* $(APF) -i $(A_IL) $(EXTAPF) $(AFLAGS)

#-----------------------------------------------------------------------------
# Targets and dependents...
#-----------------------------------------------------------------------------

FLH = ..\pjltypes.h ..\pjprotos.h ..\pjstypes.h ..\pjecodes.h ..\pjbasics.h $(LFILE)

all:  quickflc.exp playfram.exp copyflic.exp circflic.exp custom.exp ramflic.exp
	@echo Phew - made all the FlicLib examples.>all

quickflc.exp: quickflc.obj $(FLH)
	wlink @stdp.lnk FILE quickflc.obj LIB $(LFILE) NAME quickflc.exp

copyflic.exp: copyflic.obj $(FLH)
	wlink @stdp.lnk FILE copyflic.obj LIB $(LFILE) NAME copyflic.exp

circflic.exp: circflic.obj $(FLH)
	wlink @stdp.lnk FILE circflic.obj LIB $(LFILE) NAME circflic.exp

custom.exp: custom.obj farcopy.obj $(FLH)
	wlink @stdp.lnk FILE custom.obj,farcopy.obj LIB $(LFILE) NAME custom.exp

playfram.exp: playfram.obj $(FLH)
	wlink @stdp.lnk FILE playfram.obj LIB $(LFILE) NAME playfram.exp

ramflic.exp: ramflic.obj $(FLH) ..\pjfli.h
	wlink @stdp.lnk FILE ramflic.obj LIB $(LFILE) NAME ramflic.exp

