!include "..\inc\make.inc"

EXTCPF = -w3			# all warnings enabled for gluecode
C_IL = $(C_IL);..\..\;..\gluecode\;\paa\poco\poekit\inc\ # need poekit headers

OBJ 	= \
		playntil.obj \
		poeglue.obj  \
		fastclk.obj  \
		gs_poe.obj	 \
		linscale.obj \
		scaletab.obj \
		rcelcopy.obj \
		jfreadec.obj \
		jfreados.obj \
		jfwritec.obj \
		jfwritos.obj \
		#endoflist

gluepoe.lib: $(OBJ) makefile.
   del	$<
   wlib $< @&&%
$(OBJ)
%

