## makefile for Intel Code Builder

C_IL	= ..\	  # include path list for C   (format: \path\;\path\;...)
A_IL	= ..\	  # include path list for ASM (format: \path\,\path\,...)

CC	= icc
CPF = -c -d1 -n -znoalign -DFLILIB_CODE

AS	= 386asm
APF = -80386 -NOLIST -TWOCASE

LK	= icc
LPF = -m -n -s12000

.c.obj:
	$(CC) $(CPF) -I$(C_IL) $(EXTCPF) $(CFLAGS) $<

.asm.obj:
	$(AS) $< $(APF) -i $(A_IL) $(EXTAPF) $(AFLAGS)


FLH = ..\pjltypes.h ..\pjprotos.h ..\pjstypes.h ..\pjecodes.h \
	  ..\pjbasics.h ..\flic386c.lib

all: flicinfo.exe stepflic.exe flicplay.exe
	@echo Phew - made all the fliclib internal test programs.

flicinfo.exe flicinfo: flicinfo.obj $(FLH)
	$(LK) $(LPF) flicinfo.obj ..\flic386c.lib

stepflic.exe stepflic: stepflic.obj $(FLH)
	$(LK) $(LPF) stepflic.obj ..\flic386c.lib

flicplay.exe flicplay: flicplay.obj $(FLH)
	$(LK) $(LPF) flicplay.obj ..\flic386c.lib

linktest.exe linktest: linktest.obj $(FLH)
	$(LK) $(LPF) linktest.obj ..\flic386c.lib
	del linktest.exe # don't need exe, just link map
	del linktest.obj # don't need obj
