!include "\paa\make.inc"


## low level raster internal calls needed for just about anything that has 
## any raster in it

RASTLOWO = \
 cmapshif.obj custrast.obj getplane.obj grcommon.obj grc_comp.obj grcdcomp.obj\
 grcfulib.obj grctblil.obj grclib.obj grcset.obj grcrwcal.obj libdummy.obj\
 nullinit.obj nullrast.obj nullrlib.obj 

## items needed for a bytemap raster 

BYMRASTO = \
 byblirec.obj bymalloc.obj bymblock.obj bymdiagt.obj bym1blit.obj bym2blit.obj\
 bymdot.obj bymhseg.obj bymrast.obj bymtblit.obj bysetras.obj bymvseg.obj\
 byunbrun.obj byulccmp.obj bymunss2.obj

## independent bytemap raster utilities

BYMUTILO = \
 temprast.obj

## things needed for a bitmap raster does not require bytemap code *****

BITRASTO = \
 bitrast.obj bitalloc.obj
 
## things needed for a 320 X 200 mcga screen raster requires bytemap code
## but not bitmap code or bytemap utilities

MCGAO = \
 mcgadot.obj mcgacset.obj mccset64.obj mcgahseg.obj mcgarast.obj mcgadev.obj

## clipbox code is called with another raster but only needs low level code

CBOXO = \
 clipblib.obj clipbox.obj clipsafe.obj

## raster call and clipping glue. really needed for most things since a 
## raster is pretty useless without it. Its divided into little modules
## since only a small subset may be needed for an application some calls are
## made by ".asm" files these many have tested ".c" file equivalents
## as name.cc for name.asm

RASTCALLO = \
 rclclipd.obj rclclip2.obj rclip2r.obj rc_blire.obj rc_getdo.obj rc_ghseg.obj\
 rc_gvseg.obj rc_msk1bl.obj rc_msk2bl.obj rc_pdot.obj rc_phseg.obj\
 rc_pvseg.obj rc_setre.obj rc_shlin.obj rc_svlin.obj rc_swapr.obj rc_tblit.obj\
 rc_xorec.obj rcblirec.obj rcclose.obj rcdiagto.obj rcfree.obj\
 rcgetdot.obj rcghseg.obj rcgrpix.obj rcgvseg.obj rcmsk1bl.obj rcmsk2bl.obj\
 rcphseg.obj rcprpix.obj rcputdot.obj rcpvseg.obj rcset256.obj rcset64.obj\
 rcsetcol.obj rcsetras.obj rcsetrec.obj rcshline.obj rcsvline.obj rcswapr.obj\
 rctblitr.obj rculccmp.obj rcunbrun.obj rcunss2.obj rcwaitvs.obj rcxorast.obj\
 rcxorect.obj rczoombl.obj
 
## code needed to load drivers this will have to be linked with a syslib
## menulib etc to be useable

VDRIVERO = \
 vdgetmod.obj vdispopn.obj vdrclose.obj \
 vdrvinfo.obj vdrasopn.obj vdrvload.obj \
 vdrvopen.obj vdscropn.obj vdverify.obj

libs: raster.lib
	@cd
	@echo libs made

## the pj raster library that has it all

raster.lib:	makefile\
			$(RASTLOWO) rastlow.obs\
			$(BYMRASTO) bymrast.obs\
			$(BYMUTILO) bymutil.obs\
			$(BITRASTO) bitrast.obs\
			$(MCGAO)	mcgarast.obs\
			$(CBOXO)	clipbox.obs\
			$(RASTCALLO) rastcall.obs\
			$(VDRIVERO) vdriver.obs
 wlib /n raster.lib \
	 @rastlow.obs @bymrast.obs @bymutil.obs @bitrast.obs \
	 @mcgarast.obs @clipbox.obs @rastcall.obs @vdriver.obs

