!include "\paa\make.inc"


## low level raster internal calls needed for just about anything that has 
## any raster in it

RASTLOWO = \
 cmapshif.obj getplane.obj grcommon.obj grc_comp.obj grcdcomp.obj\
 grcfulib.obj grclib.obj grcset.obj grcrwcal.obj libdummy.obj\
 nullinit.obj nullrast.obj nullrlib.obj 

## items needed for a bytemap raster 

BYMRASTO = \
 bymalloc.obj bymrast.obj

## independent bytemap raster utilities

BYMUTILO = \
 temprast.obj

## things needed for a bitmap raster does not require bytemap code *****

BITRASTO = \
 bitrast.obj bitalloc.obj
 
## things needed for a 320 X 200 mcga screen raster requires bytemap code
## but not bitmap code or bytemap utilities

MCGAO = \
 mcgadot.obj mcgacset.obj mccset64.obj mcgahseg.obj mcgarast.obj mcgadev.obj

## clipbox code is called with another raster but only needs low level code

CBOXO = \
 clipbox.obj

## raster call and clipping glue. really needed for most things since a 
## raster is pretty useless without it. Its divided into little modules
## since only a small subset may be needed for an application some calls are
## made by ".asm" files these many have tested ".c" file equivalents
## as name.cc for name.asm

RASTCALLO = \
 rastcall.obj\
 rclclipd.obj rclclip2.obj rclip2r.obj rc_blire.obj\
 rc_swapr.obj rc_tblit.obj\
 rcblirec.obj rcclose.obj rcfree.obj\
 rcghseg.obj rcgrpix.obj rcgvseg.obj rcmsk1bl.obj rcmsk2bl.obj\
 rcphseg.obj rcprpix.obj rcpvseg.obj\
 rcsetrec.obj rcshline.obj rcsvline.obj rcswapr.obj\
 rctblitr.obj rcxorast.obj\
 rcxorect.obj rczoombl.obj
 
## code needed to load drivers this will have to be linked with a syslib
## menulib etc to be useable

VDRIVERO = \
 vdgetmod.obj vdispopn.obj vdrclose.obj \
 vdrvinfo.obj vdrasopn.obj vdrvload.obj \
 vdrvopen.obj vdscropn.obj vdverify.obj

libs: raster.lib
	@cd
	@echo libs made

## the pj raster library that has it all

raster.lib:	makefile\
			$(RASTLOWO) rastlow.obs\
			$(BYMRASTO) bymrast.obs\
			$(BYMUTILO) bymutil.obs\
			$(BITRASTO) bitrast.obs\
			$(MCGAO)	mcgarast.obs\
			$(CBOXO)	clipbox.obs\
			$(RASTCALLO) rastcall.obs\
			$(VDRIVERO) vdriver.obs
 wlib /n raster.lib \
	 @rastlow.obs @bymrast.obs @bymutil.obs @bitrast.obs \
	 @mcgarast.obs @clipbox.obs @rastcall.obs @vdriver.obs

