!include "..\inc\make.inc"

EXE  = mov.pdr
OBJ  = movie.obj movutil.obj shoframe.obj bytecopy.obj
LOBJ = movie.obj,movutil.obj,shoframe.obj,bytecopy.obj

$(EXE): $(OBJ)
	wlink @pdr.lnk FILE $(LOBJ) NAME $(EXE)
	copy $(EXE) \paa\resource
