#CFLAGS= -d2

!include "\paa\make.inc"

O=  amifonts.obj bit2alph.obj cfont.obj \
 fontdev.obj hpjet.obj vfont.obj stfont.obj sail.obj sixhi.obj\
 wwcountl.obj wwcstart.obj wwjustif.obj wwline.obj wwtext.obj type1.obj




libs: fontlib.lib
	@cd
	@echo libs made

fontlib.lib: 	$(O)\
		 		fontlib.obs
	wlib /n fontlib.lib @fontlib.obs 
