
#define I_OPAQUE 0
#define I_VGRAD 1
#define I_HGRAD 2
#define I_LGRAD 3
#define I_GLAZE 4
#define I_GLASS	6
#define I_SCRAPE 7
#define I_XOR 8
#define I_JUMBLE 9
#define I_ADD 10
#define I_GLOW 11
#define I_TILE	12
#define I_SPARK 13
#define I_SPLIT 14
#define I_UNZAG 15
#define I_HOLLOW 16
#define I_BRIGHT 17
#define I_GREY 18
#define I_SWEEP 19
#define I_CLOSE 20
#define I_DARK 21
#define I_EMBOSS 22
#define I_PULL 23
#define I_SMEAR 24
#define I_RGRAD 25
