!include "..\inc\make.inc"

DRIVERO = \
 mmmmport.obj mmmmblfr.obj mmmmblin.obj mmmmblto.obj mmmmdhli.obj mmmmdot.obj\
 mmmmhseg.obj mmmmmsk1.obj mmmmmsk2.obj mmmmss2.obj mmmmrect.obj mmmmsetc.obj\
 mmmmsync.obj mmmmdev.obj mmmmrast.obj

8514a.drv: $(DRIVERO) files.lnk
#	fastlink ..\lib\rexentry.obj @driver.lnk -RELEXE 8514a.drv
	wlink @..\usual.lnk NAME $< FILE @files.lnk
	copy $< \paa\resource

