!include "\paa\make.inc"
	

libs: macinput.lib input.lib
	@cd
	@echo lib made

## object files dependent on release.h

input.obj: $(IL)release.h

## low level dos input interfaces assembler code

LOWDOSO = \
 comexist.obj doscomm.obj doskeyis.obj doskeyin.obj doskeysh.obj doswtkey.obj 

INPUTHIO = \
 inwclick.obj\
 inwaitup.obj\
 inwpenup.obj\
 inwtany.obj\
 idriver.obj\
 idrivcfg.obj\
 keyidr.obj\
 lodos.obj\
 mouseidr.obj\
 reponpdn.obj\
 upcinkey.obj\
 waitask.obj

##**** input library for pj with loadable input drivers and NO macro handling

INPUTO = abortpol.obj input.obj

input.lib:	makefile\
			$(LOWDOSO) lowdos.obs\
			$(INPUTHIO) inputhi.obs\
			$(INPUTO) input.obs
 wlib /n input.lib @lowdos.obs @input.obs @inputhi.obs

##**** input library for pj with loadable input drivers and macro handling

MACINPUTO = macinput.obj

macinput.obj: input.c $(IL)release.h
	 $(CC) input.c $(CPF) -dINPUT_MACROS -fo=$*.obj

macinput.lib:	makefile\
				$(LOWDOSO) lowdos.obs\
				$(INPUTHIO) inputhi.obs\
				$(MACINPUTO) macinput.obs
 wlib /n macinput.lib @lowdos.obs @macinput.obs @inputhi.obs


