!include "\paa\rexlib\inc\make.inc"

# add -s (disable stack overflow checks) to avoid undefined reference to _end
CPF = $(CPF) -s

RD = \paa\resource\\


all: $(RD)key.idr $(RD)mmouse.idr $(RD)summa.idr $(RD)wacom.idr 
	@echo made all input drivers

$(RD)key.idr: key.obj lokey.obj
	wlink @usual.lnk NAME $(RD)key.idr FILE key.obj,lokey.obj

$(RD)mmouse.idr: mmouse.obj lomouse.obj
	wlink @usual.lnk NAME $(RD)mmouse.idr FILE mmouse.obj,lomouse.obj

$(RD)summa.idr: summa.obj doscomm.obj
	wlink @usual.lnk NAME $(RD)summa.idr FILE summa.obj,doscomm.obj

$(RD)wacom.idr: wacom.obj doscomm.obj lokey.obj 
	wlink @usual.lnk NAME $(RD)wacom.idr FILE wacom.obj,doscomm.obj,lokey.obj

