VERSION = 16

!include "..\inc\make.inc"

EXTCPF = -i..\drvcomn\		# add drvcomn dir to C include path
EXTAPF = -i ..\drvcomn\ 	# add drvcomn dir to ASM include path

VESADIR = ..\vesa\			# where to find vesa pieces

# LIST OF OBJECT FILES

VESALIB  = $(VESADIR)vesa.lib

DRIVERO  = svgavdev.obj svgaintf.obj
DRIVERL  = svgavdev.obj,svgaintf.obj

COMMONO  = ..\drvcomn\drvcomn.lib $(VESALIB)
COMMONL  = ..\drvcomn\drvcomn.lib,$(VESALIB)

SOURCE1  = svgavdev.c svgaintf.asm
EXTRAS	 = *.h *.i *.lnk makefile. versions.doc torture.dat torture.log

# LINK RULES

supervga.drv: $(DRIVERO) $(COMMONO)
#	fastlink ..\lib\rexentry.obj @driver.lnk -l $(VESALIB) -RELEXE supervga.drv
	wlink @std.lnk NAME supervga.drv LIB $(COMMONL) FILE $(DRIVERL)
	copy supervga.drv \paa\resource\supervga.drv

archive:
	zip svga$(VERSION) $(SOURCE1) $(EXTRAS)
	del tort$(VERSION).log
	ren torture.log tort$(VERSION).log
