#
# makefile for video driver torture program...
#

VERSION = 113

EXTCPF = /DVRSN_NUM=$(VERSION) /w3

!include "\paa\inc\make.inc"

OBJ1   = torture.obj pjstubs.obj chkdev.obj utlrast.obj chkrast1.obj chkrdots.obj
OBJ2   = chkrsegs.obj chkrline.obj chkrrect.obj chkrmask.obj chkrcolr.obj
OBJ3   = chkrblit.obj chkrtblt.obj chkrswap.obj chkrxorr.obj chkrzoom.obj
OBJ4   = chkrplay.obj getflist.obj flicinfo.obj
SRC1   = torture.c pjstubs.c chkdev.c utlrast.c chkrast1.c chkrdots.c
SRC2   = chkrsegs.c chkrline.c chkrrect.c chkrmask.c chkrcolr.c
SRC3   = chkrblit.c chkrtblt.c chkrswap.c chkrxorr.c chkrzoom.c
SRC4   = chkrplay.c getflist.c flicinfo.c
HDR    = torture.h
EXTRAS = torture.lnk makefile versions.doc ????flic.dir

torture.exp: $(OBJ1) $(OBJ2) $(OBJ3) $(OBJ4)
	wlink @torture.lnk

$(OBJ1) $(OBJ2) $(OBJ3) $(OBJ4): $(HDR)

archive:
	zip tort$(VERSION) $(SRC1) $(SRC2)
	zip tort$(VERSION) $(SRC3) $(SRC4)
	zip tort$(VERSION) $(HDR)  $(EXTRAS)
