
!include "\paa\make.inc"

PJLIBS = \paa\rastlib\raster.lib\
 \paa\util\trdutil.lib\
 \paa\rastlib\raster.lib\
 \paa\gfx\gfx.lib\
 \paa\fileio\trdfile.lib\
 \paa\rexlib\rexhost.lib\
 \paa\input\input.lib\
 \paa\fli\pjfli.lib\
 \paa\wndo\wndolib.lib\
 \paa\menus\menulib.lib\
 \paa\softmenu\softmenu.lib


all: \paa\aniplay.exp stepper.exp

PLAYERO = doscript.obj errors.obj player.obj playfli.obj playpull.obj\
 playmenu.obj playanim.obj token.obj pjstubs.obj


\paa\aniplay.exp: player.lnk $(PLAYERO) $(PJLIBS)
	wlink @player.lnk option map NAME \paa\aniplay.exp

STEPPERO = stepper.obj

stepper.exp: stepper.lnk $(STEPPERO)
	wlink @stepper.lnk OPTION map

playpull.obj: playpull.c $(IL)release.h
	$(CC) $*.c $(CPF)


