!include "..\..\inc\make.inc"

L = ..\\

libs: built_asms $(L)aasyslib.lib
	@cd

## built assembler modules 

BASMS = malloc.asm zalloc.asm free.asm memset.asm memcpy.asm memcmp.asm\
 strcpy.asm strlen.asm strcmp.asm getpsuff.asm getpname.asm rex_load.asm\
 rex_free.asm rexlload.asm rexlinit.asm rexlfree.asm pj_ioerr.asm pj_open.asm\
 pj_creat.asm pj_close.asm pj_read.asm pj_write.asm pj_seek.asm pj_tell.asm\
 pj_delet.asm pj_renam.asm pj_exist.asm boxf.asm clock.asm

built_asms: $(BASMS)
	@donothin

clock.asm: makecall.bat sljump.i
	makecall pj_clock_1000 clock

boxf.asm: makecall.bat sljump.i
	makecall boxf

malloc.asm: makecall.bat sljump.i
	makecall malloc
 
zalloc.asm: makecall.bat sljump.i
	makecall zalloc
 
free.asm: makecall.bat sljump.i
	makecall free
 
memset.asm: makecall.bat sljump.i
	makecall memset
 
memcpy.asm: makecall.bat sljump.i
	makecall memcpy
 
memcmp.asm: makecall.bat sljump.i
	makecall memcmp
 
strcpy.asm: makecall.bat sljump.i
	makecall strcpy
 
strlen.asm: makecall.bat sljump.i
	makecall strlen
 
strcmp.asm: makecall.bat sljump.i
	makecall strcmp
 
getpsuff.asm: makecall.bat sljump.i
	makecall pj_get_path_suffix getpsuff
 
getpname.asm: makecall.bat sljump.i
	makecall pj_get_path_name getpname
 
rex_load.asm: makecall.bat sljump.i
	makecall pj_rex_load rex_load
 
rex_free.asm: makecall.bat sljump.i
	makecall pj_rex_free rex_free
 
rexlload.asm: makecall.bat sljump.i
	makecall pj_rexlib_load rexlload
 
rexlinit.asm: makecall.bat sljump.i
	makecall pj_rexlib_init rexlinit
 
rexlfree.asm: makecall.bat sljump.i
	makecall pj_rexlib_free rexlfree
 
pj_ioerr.asm: makecall.bat sljump.i
	makecall pj_ioerr
 
pj_open.asm: makecall.bat sljump.i
	makecall pj_open
 
pj_creat.asm: makecall.bat sljump.i
	makecall pj_create pj_creat
 
pj_close.asm: makecall.bat sljump.i
	makecall pj_close
 
pj_read.asm: makecall.bat sljump.i
	makecall pj_read
 
pj_write.asm: makecall.bat sljump.i
	makecall pj_write
 
pj_seek.asm: makecall.bat sljump.i
	makecall pj_seek
 
pj_tell.asm: makecall.bat sljump.i
	makecall pj_tell
 
pj_delet.asm: makecall.bat sljump.i
	makecall pj_delete pj_delet
 
pj_renam.asm: makecall.bat sljump.i
	makecall pj_rename pj_renam
 
pj_exist.asm: makecall.bat sljump.i
	makecall pj_exists pj_exist
 
# *** object files for "_a_a_syslib" calls ***

SYSLIBO = \
clock.obj boxf.obj free.obj getpname.obj getpsuff.obj loadpath.obj \
rexlload.obj malloc.obj memcmp.obj memcpy.obj \
memset.obj pj_close.obj pj_creat.obj pj_delet.obj \
pj_exist.obj pj_ioerr.obj pj_open.obj pj_read.obj \
pj_renam.obj pj_seek.obj pj_tell.obj pj_write.obj \
rex_free.obj rex_load.obj rexlfree.obj rexlinit.obj \
strcmp.obj strcpy.obj strlen.obj zalloc.obj 

$(SYSLIBO): $(IL)aasyslib.i

# *** syslib only library for linking with video driver code ***

$(L)aasyslib.lib:	$(BASMS) $(SYSLIBO)\
					aasyslib.obs
 del $(L)aasyslib.lib
 wlib $(L)aasyslib.lib @aasyslib.obs 

