CFLAGS = -d2
!include "\paa\make.inc"

libs: gfx.lib
	@cd
	@echo libs made

IMAGEO = \
 imagblit.obj\
 imagrast.obj\
 imatblit.obj\
 imsctbli.obj

RASTGFXO = \
 rgblitmv.obj\
 rgclrast.obj\
 rgdolbh.obj\
 rgfndclp.obj\
 rghsuncp.obj\
 rglinein.obj\
 rgmcused.obj\
 rgsetlbh.obj\
 rgublit.obj\
 rgxlatra.obj

PBLITO = \
 pbabblit.obj\
 pbblit.obj\
 pbtblxll.obj\
 pbubliln.obj\
 pbublxln.obj\
 pbxlatbl.obj\

RCELO = \
 rcelcopy.obj\
 rcelfree.obj\
 rcenvirt.obj\
 rcgetdis.obj\
 rcgetbym.obj\
 rcgetvd.obj\
 rcmapget.obj\
 rcopenvd.obj\
 rcopmcga.obj\
 rcgetmcg.obj\
 rcopnbym.obj\
 rcopndis.obj\
 rcvrtual.obj\
 rcustopn.obj\
 rcustget.obj

## low level rectangle manipulation

RECTANGO = \
 rebclip0.obj\
 rebclipd.obj\
 recandcr.obj\
 recbclip.obj\
 recpinsi.obj\
 recquad9.obj\
 recrcode.obj\
 recrolap.obj\
 recrtofr.obj\
 recrtor.obj\
 recsclip.obj\
 rectand.obj\
 rectptin.obj\
 recttocr.obj\
 recttofr.obj\
 refratcr.obj\
 refratfr.obj\
 refrator.obj\
 reswaclp.obj

## graphics library routine to draw lines, circles etc, etc

GFXLIBO = \
 bithline.obj\
 cmapcopy.obj\
 cmapload.obj\
 cmapsame.obj\
 cmapstuf.obj\
 cmapswap.obj\
 cmchksum.obj\
 cmclone.obj\
 cmcloses.obj\
 cmtblend.obj\
 cmclosex.obj\
 cmhlssub.obj\
 cmhlsrgb.obj\
 cmrgbhls.obj\
 cmgetcol.obj\
 cminctab.obj\
 cmsetcol.obj\
 fgftiang.obj\
 fgitfang.obj\
 fgpiclip.obj\
 fgrotate.obj\
 gfxlib.obj\
 gl_sclin.obj\
 gl_sdot.obj\
 gl_sline.obj\
 glcframe.obj\
 glcircle.obj\
 glcline.obj\
 glcvect.obj\
 gldcircl.obj\
 gldrquad.obj\
 gldoval.obj\
 glline.obj\
 glmaxlin.obj\
 glrcircl.obj\
 glrtoxyz.obj\
 glsqpoly.obj\
 linscale.obj\
 pgconcav.obj\
 pgconvex.obj\
 pghollow.obj\
 pgfilled.obj\
 pgminmax.obj\
 pgsolidc.obj\
 rastrans.obj\
 scalebli.obj\
 scaletab.obj


gfx.lib:	makefile\
			$(IMAGEO) image.obs\
			$(RASTGFXO) rastgfx.obs\
			$(PBLITO) procblit.obs\
			$(RCELO) rcel.obs\
			$(RECTANGO) rectang.obs\
			$(GFXLIBO) gfxlib.obs
 wlib /n gfx.lib \
	@image.obs @rastgfx.obs @procblit.obs @rcel.obs @rectang.obs @gfxlib.obs

