!include "\paa\make.inc"

O = choices.obj feelme.obj icbvwait.obj menus.obj pull.obj\
 pullsee.obj qnumber.obj qscroll.obj qstring.obj scroller.obj seeme.obj\
 icbcontb.obj icbbool.obj icbvbool.obj icbmulti.obj icb_boxf.obj icbvcont.obj\
 slider.obj stringq.obj titlebar.obj titclose.obj wndoio.obj pullid.obj\
 seepath.obj

libs: menulib.lib 
	@cd
	@echo made

menulib.lib: $(O)\
		 	menulib.obs
	wlib /n menulib.lib @menulib.obs 
