!include ..\inc\make.inc

EXE  = patch10a.poe
OBJ  = patch10a.obj poeshell.obj
LOBJ = patch10a.obj,poeshell.obj

$(EXE): $(OBJ)
	wlink @poe.lnk FILE $(LOBJ) NAME $(EXE)
	copy patch10a.obj ..\lib
	copy patch10a.h   ..\inc
