!include ..\inc\make.inc

CFLAGS = -ez

VERSION = 1

EXE = eco.poe
OBJ = eco.obj

$(EXE): $(OBJ)
	fastlink $(REXSTARTUP) @eco.lnk -RELEXE $(EXE)

archive:
	zip eco$(VERSION) *.c *.h *.i* *.asm *.poc makefile. *.lnk
