
CFLAGS= -c -Ic:\tc -I..

.c.obj:
	tcc $(CFLAGS) $*.c
.asm.obj:
	masm /Ml $*.asm;
.c.exe:
	tcc $(CFLAGS) $*.c
	tlink c:\tc\c0s $*.obj, $*, $*, c:\tc\emu c:\tc\maths \
	c:\tc\cs

makeicon: makeicon.exe
	@echo made it

makemenu: makemenu.exe
	@echo made it

makepull: makepull.exe
	@echo made it

