!include ..\inc\make.inc
CFLAGS=/w3

EXE  = colorutl.poe
OBJ  = colorutl.obj poclosec.obj rgbhls.obj
LOBJ = colorutl.obj,poclosec.obj,rgbhls.obj,..\lib\patch10a.obj

$(EXE): $(OBJ)
	wlink @poe.lnk FILE $(LOBJ) NAME $(EXE)
