OBJ1 = \
dosecode.obj \
doserror.obj \
dosgvmod.obj \
doskeyin.obj \
doskeyis.obj \
dossvmod.obj \
dosvblan.obj \
fastclk.obj  \
imusclby.obj \
membcomp.obj \
membcont.obj \
membcopy.obj \
membsame.obj \
membset.obj \
memdcomp.obj \
memdstuf.obj \
memfreez.obj \
memgfree.obj \
memnulod.obj \
memwcomp.obj \
memwcopy.obj \
memwstuf.obj \
memxlate.obj \
memxorbt.obj \
ptrenorm.obj \
#endoflist
