!include "\paa\make.inc"

VERSION = 5  # used in creating backup filenames

PJLIBS = \paa\rastlib\raster.lib\
 \paa\util\trdutil.lib\
 \paa\rastlib\raster.lib\
 \paa\gfx\gfx.lib\
 \paa\fileio\trdfile.lib\
 \paa\rexlib\rexhost.lib\
 \paa\input\input.lib\
 \paa\fli\pjfli.lib\
 \paa\wndo\wndolib.lib\
 \paa\menus\menulib.lib\
 \paa\softmenu\softmenu.lib


OBJECTS = convert.obj convpdr.obj convpull.obj convflic.obj convrgb.obj \
	ccache.obj bhash.obj ghash.obj bbhash64.obj \
	convmove.obj scale.obj rgbcmap.obj \
	flipdr.obj pjstubs.obj

SOURCE1 = convert.c convpdr.c convpull.c convflic.c convrgb.c
SOURCE2 = ccache.c bhash.c ghash.c bbhash64.c convmove.c
SOURCE3 = scale.c rgbcmap.c flipdr.c
EXTRAS	= *.h convert.lnk makefile make.bat versions.doc

convert convert.exp: convert.lnk $(OBJECTS) $(PJLIBS)
	wlink @convert.lnk option map

archive:
	zip convert$(VERSION) $(SOURCE1)
	zip convert$(VERSION) $(SOURCE2)
	zip convert$(VERSION) $(SOURCE3) $(EXTRAS)
