!include "..\inc\make.inc"

EXE  = rnd.pdr
OBJ  = rnd.obj rndutil.obj bytecopy.obj imusclby.obj convex.obj concave.obj polygon.obj
LOBJ = rnd.obj,rndutil.obj,bytecopy.obj,imusclby.obj,convex.obj,concave.obj,polygon.obj

$(EXE): $(OBJ)
	wlink @pdr.lnk FILE $(LOBJ) NAME $(EXE)
	copy $(EXE) \paa\resource
