!include "..\inc\make.inc"

DRIVERO = device.obj raster.obj \
evgabank.obj evgacmap.obj evgaddhl.obj evgadhli.obj \
evgagdot.obj evgageth.obj evgamsk1.obj evgapdot.obj \
evgaputh.obj evgass2.obj evgasubs.obj evgaunc2.obj \
evgauncc.obj evgaxhli.obj unss2.obj

evga.drv: $(DRIVERO)
#	fastlink ..\lib\rexentry.obj @driver.lnk -RELEXE evga.drv
	wlink @..\usual.lnk NAME $< FILE @files.lnk
	copy $< \paa\resource\evga.drv

