#-----------------------------------------------------------------------------
# Watcom C -3r Makefile for 3dlook example programs.
#-----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
# These macros and rules are for the watcom 386 c compiler and Turbo make...
#-----------------------------------------------------------------------------

C_IL	= ..\ # include files path for C
A_IL	= ..\ # include files path for ASM

LFILE	= ..\flc386wr.lib

CC	= wcc386
CPF = -j -ox -fpi -w3 -3r

.c.obj:
	$(CC) $*.c $(CPF) -I$(C_IL) $(EXTCPF) $(CFLAGS)

AS	= 386asm
APF = -80386 -NOLIST -TWOCASE

.asm.obj:
	$(AS) $* $(APF) -i $(A_IL) $(EXTAPF) $(AFLAGS)

#-----------------------------------------------------------------------------
# Targets and dependents...
#-----------------------------------------------------------------------------

FLH = ..\pjltypes.h ..\pjprotos.h ..\pjstypes.h ..\pjecodes.h ..\pjbasics.h


3dlook.exp: 3dlook.obj expandat.obj $(FLH)
	wlink @stdw.lnk FILE 3dlook.obj,expandat.obj LIB $(LFILE) NAME 3dlook.exe

