#CFLAGS= -d2
!include "\paa\make.inc"

libs: trdfile.lib
	 @cd
 	 @echo libs made

## dos file io modules ****

DOSO = \
 dosctflp.obj dosdfree.obj\
 dosetdir.obj dosetdta.obj dosfirst.obj dosgetdr.obj dosgtdir.obj\
 dosisdev.obj dosmkdir.obj dosnext.obj\
 dossetdr.obj dosetdri.obj

## "j" dos device and directory level calls that call dos only 

JFDEVO = \
 jdevget.obj jdevset.obj jdirset.obj jdevlist.obj jdevsget.obj fs_dos.obj

## file name parseing modules (string functions etc) ***

FPARSEO = \
 filepath.obj \
 fpaddsub.obj fparsdev.obj fparsdir.obj fpconcat.obj fpdirlen.obj\
 fpfulfil.obj fpgetdir.obj fpgetful.obj fpgetnam.obj fpincnam.obj\
 fpissuff.obj fpmkfile.obj fpnmerge.obj fpnsplit.obj fppfxlen.obj\
 fpremnam.obj fpspltcp.obj fpspltpa.obj fpsuffix.obj fpsufget.obj\
 fpsufhas.obj fpsuffin.obj fpsufrem.obj fpnamein.obj fpsetnam.obj 

## jfile modules that only handle dos files, NO internal ram disk NO temp
## file handling.
## note dfgetdrv is a filepath module but is here because of the temp drive 
## handling

JFILEDO = \
 dfdelete.obj dfexists.obj dfile.obj dfisfixd.obj dfread.obj dfrename.obj\
 dfseek.obj dfsize.obj dfstdio.obj dftell.obj dftrdmem.obj\
 dftrdumm.obj dfwrite.obj dfgetdrv.obj

## jfile io modules that have ram disk temp file handling and temp file handing
## this calls doso modules for operating system calls

## note fpgetdrv is a filepath module but is here because of the temp drive 
## handling

JFILETRO = \
 jfile.obj tfile.obj fpgetdrv.obj

## jfile utilities that call jfile functions ****

JFUTILSO = \
 aasyslib.obj \
 jfchunk.obj jfcopyin.obj jfcpdat.obj jfcpfile.obj \
 jfgulp.obj jfinsert.obj jfpisfix.obj \
 jfwrite0.obj
 
## XFILE
XFILEO = xfile.obj

xfile.obj: xfile.c
	 $(CC) xfile.c $(CPF) -fo=$*.obj

#** library with temp and ram file handling file system and all utilities *

trdfile.lib: makefile\
			 $(DOSO) dos.obs\
			 $(JFDEVO) jdevice.obs\
			 $(FPARSEO) fparse.obs\
			 $(JFILETRO) jfiletrd.obs\
			 $(JFUTILSO) jfutils.obs\
			 $(XFILEO) xfile.obs
 wlib /n trdfile.lib \
	@dos.obs @jdevice.obs @fparse.obs @jfiletrd.obs \
	@jfutils.obs @xfile.obs
