VERSION = 24

!include "..\inc\make.inc"

EXTCPF = -i..\drvcomn\		# add drvcomn dir to C include path
EXTAPF = -i ..\drvcomn\ 	# add drvcomn dir to ASM include path

# LIST OF OBJECT FILES

DRIVEROBJ	= vesavdev.obj
DRIVERLIB	= vesaintf.obj vesamode.obj plralloc.obj plint10.obj
COMMONOBJ	= ..\drvcomn\drvcomn.lib

SOURCE1 = *.c *.asm
EXTRAS	= *.h *.i *.lnk *.obs makefile torture.* versions.doc

# LINK RULES

test.drv: $(DRIVEROBJ) $(COMMONOBJ) vesa.lib makefile
	wlink @std.lnk NAME test.drv LIB $(COMMONOBJ),vesa.lib FILE $(DRIVEROBJ)
#	fastlink ..\lib\rexentry.obj @driver.lnk -RELEXE test.drv -MAP vesa.map
	copy test.drv \paa\resource\test.drv

vesa.lib: $(DRIVERLIB)
	wlib /n vesa.lib $(DRIVERLIB)

archive:
	zip vesa$(VERSION) $(SOURCE1) $(EXTRAS)
	del tort$(VERSION).log
	ren torture.log tort$(VERSION).log
