!include "..\inc\make.inc"

OBJ = device.obj raster.obj hardware.obj rect.obj dot.obj uncomp.obj \
xor.obj rectpix.obj

compaq.drv: $(OBJ)
	wlink @..\usual.lnk NAME $< FILE @files.lnk
#	copy $< \paa\resource


