!include ..\inc\make.inc

VERSION = 8

EXE = pdracces.poe
OBJ = pdracces.obj rgb2cmap.obj ccache.obj packcmap.obj strfuncs.obj closestc.obj
LOBJ = pdracces.obj,rgb2cmap.obj,ccache.obj,packcmap.obj,strfuncs.obj,closestc.obj

$(EXE): $(OBJ)
	wlink @poe.lnk FILE $(LOBJ) NAME $(EXE)

archive:
	zip pdracc$(VERSION) *.c *.h *.i* *.asm *.poc makefile. *.lnk
