!include "\paa\make.inc"

O = softmenu.obj loadstri.obj loadpull.obj dstring.obj \
	dstrgets.obj keyequiv.obj pullfmt.obj softok.obj \
	defpull.obj serrtext.obj namestri.obj snamestr.obj sofpanel.obj

objlib: softmenu.lib
	@cd
	@echo all made

softmenu.lib: $(O)\
			  softmenu.obs
	wlib /n softmenu.lib @softmenu.obs 
