!include "..\inc\make.inc"

C_IL = $(C_IL);..\drvcomn\	   # add drvcomn dir to C include path
A_IL = $(A_IL),..\drvcomn\	   # add drvcomn dir to ASM include path

OBJ = svgavdev.obj svgaintf.obj

svgavdev.lib: $(OBJ) makefile.
	del  $<
	wlib $< @&&%
$(OBJ)
%
