!include "..\..\inc\make.inc"

L = ..\\

libs: $(L)gfxlib.lib
	@cd

# *** object files for "_a_a_syslib" calls ***

GFXLIBO =  _blitrec.obj\
 _swaprec.obj _tblirec.obj blitrect.obj clearas.obj closeras.obj closrcel.obj\
 cmallocc.obj cmapcopy.obj cmapfree.obj cmapload.obj freerast.obj freercel.obj\
 get_hseg.obj get_vseg.obj getbymrc.obj getrpix.obj makecbox.obj mask1bli.obj\
 mask2bli.obj\
 opnbymrc.obj put_hseg.obj put_vseg.obj putrpix.obj rc_getdo.obj rc_ghseg.obj\
 rc_grpix.obj rc_gvseg.obj rc_msk1b.obj rc_msk2b.obj rc_pdot.obj rc_phseg.obj\
 rc_prpix.obj rc_pvseg.obj rc_setre.obj rc_shlin.obj rc_svlin.obj rc_xorec.obj\
 rcgetdot.obj rcputdot.obj rcset256.obj rcset64.obj rcsetcol.obj rcsetras.obj\
 rculccmp.obj rcunbrun.obj rcunss2.obj rcwaitvs.obj set_rect.obj sethline.obj\
 setvline.obj swaprect.obj tblirec.obj virtuarc.obj xor_rast.obj xor_rect.obj\
 zoomblit.obj cmapcopy.obj

$(GFXLIBO): $(IL)gfxlib.i

$(L)gfxlib.lib:	$(GFXLIBO)\
				gfxlib.obs
 del $(L)gfxlib.lib
 wlib $(L)gfxlib.lib @gfxlib.obs 

