!include "\paa\make.inc"

# add -s (disable stack overflow checks) to avoid undefined reference to _end
CPF = $(CPF) -s

.obj.ink: 
#	fastlink @ink.lnk $*.obj -RELEXE $*.ink
	wlink @usual.lnk NAME $*.ink FILE $*.obj
	copy $*.ink \paa\resource

all: or.obj and.obj merge.obj subtract.obj slice.obj smooth.obj unbuzz.obj\
	 or.ink and.ink merge.ink subtract.ink slice.ink smooth.ink unbuzz.ink\
	 cloud.obj sharpen.obj quantize.obj \
	 cloud.ink sharpen.ink quantize.ink
	@cd
	@echo all made

cloud.ink or.ink and.ink merge.ink subtract.ink slice.ink \
smooth.ink unbuzz.ink quantize.ink: \
	\paa\rexlib\rexentry.obj\
	\paa\rexlib\aasyslib.lib
