CFLAGS= -d2
!include "make.inc"

allmem.exp: allmem.obj
	wlink @allmem.lnk

testrex: test.rex

test.exp: test.obj testmain.obj testasm.obj
	wlink @test.lnk option map
	@echo objlib made

test.rex: testrex.obj dataend.obj
	fastlink rexentry.obj @testrex.lnk -RELEXE test.rex

dpmimem.exp dpmimem: dpmimem.obj dpmiutil.obj
	wlink SYSTEM pharlap debug all FILE dpmimem.obj,dpmiutil.obj NAME dpmimem.exp

#	wlink @testrex.plk
#	fastlink \paa\rexlib\rexentry.obj @testrex.lnk -RELEXE test.rex
